// <auto-generated />
namespace AluminiManagement.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class removeEmailLengthFromTbl_memeberform : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removeEmailLengthFromTbl_memeberform));
        
        string IMigrationMetadata.Id
        {
            get { return "201804151328050_removeEmailLengthFromTbl_memeberform"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
